/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bpw1vKbIj5v
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Label } from "@/components/ui/label";
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function CallbackForm() {
  return (
    <section className="md:container my-[100px] block flex-col items-center justify-center md:flex">
      <div className="w-full max-w-6xl rounded-lg bg-[#E7FAEC] py-16 px-5 lg:p-16">
        <div className="flex flex-col gap-8 md:flex-row">
          <div>
            <h2 className="mb-2 text-3xl font-bold">Request a Callback</h2>
            <p className="text-gray-600">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
              porta efficitur lectus sed pharetra. Nulla facilisis eros at ipsum
              mattis, eleifend posuere enim.
            </p>
          </div>
          <div className="w-full rounded-lg bg-white p-6 md:min-w-[400px]">
            <form className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="course">Course</Label>
                <Select>
                  <SelectTrigger id="course">
                    <SelectValue placeholder="Select a course" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="course1">Course 1</SelectItem>
                    <SelectItem value="course2">Course 2</SelectItem>
                    <SelectItem value="course3">Course 3</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="name">Name*</Label>
                <Input id="name" placeholder="Full Name" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="email">Email*</Label>
                <Input id="email" placeholder="Email" type="email" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="phone">Phone*</Label>
                <Input id="phone" placeholder="Phone Number" type="tel" />
              </div>
              <Button className="w-full">Submit</Button>
            </form>
          </div>
        </div>
      </div>
    </section>
  );
}
