/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fkC6Vb5AOy5
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Button } from "@/components/ui/button";
import { AvatarImage, Avatar } from "@/components/ui/avatar";
import { HeartIcon, StarIcon } from "lucide-react";
const IconGroup = ({
  IconComponent,
  count,
  fillColor,
  className,
}: {
  IconComponent: React.ElementType;
  count: number;
  fillColor: string;
  className?: string;
}) => (
  <div className="flex items-start">
    {Array.from({ length: count }).map((_, index) => (
      <IconComponent
        key={index}
        fill={fillColor}
        floodColor={fillColor}
        className={`mr-1 ${className}`}
      />
    ))}
  </div>
);

const StatBlock = ({
  value,
  IconComponent,
  iconCount,
  fillColor,
  description,
}: {
  value: number | string;
  IconComponent: React.ElementType;
  iconCount: number;
  fillColor: string;
  description: string;
}) => (
  <div className="flex flex-col items-start justify-start gap-2">
    <div className="text-6xl font-bold">{value}</div>
    <IconGroup
      IconComponent={IconComponent}
      count={iconCount}
      fillColor={fillColor}
      className={fillColor}
    />
    <div className="text-sm">{description}</div>
  </div>
);

export function Community() {
  return (
    <section className="container my-20 bg-[#FEE4D4] p-8 py-16">
      <div className="mx-auto grid max-w-6xl grid-cols-1 items-center gap-8 md:grid-cols-2 lg:grid-cols-2">
        <div className="lg:space-b-4">
          <h3 className="mb-[10px] mt-[20px] box-border bg-[rgb(250,223,202)] text-[36px] font-semibold leading-[48px] text-[rgb(51,51,51)]">
            Trusted by the 1800+ happy students and online users since 2023
          </h3>

          <Button className="rounded-md border-none bg-[#10B981] px-6 py-3 font-semibold text-white hover:bg-[#059669]">
            Join our community
          </Button>
        </div>
        <div className="flex flex-col items-start justify-start gap-5">
          <div className="grid grid-cols-2 items-center gap-16">
            <StatBlock
              value="1K+"
              IconComponent={HeartIcon}
              iconCount={5}
              fillColor="#FF3E3E"
              description="active learners worldwide"
            />
            <StatBlock
              value="4.8"
              IconComponent={StarIcon}
              iconCount={5}
              fillColor="#FFC107"
              description="based on 20,000+ reviews"
            />
          </div>
          <div className="flex items-center justify-start gap-4 rounded-lg bg-white p-2 shadow-md">
            <Avatar>
              <AvatarImage
                alt="User testimonial"
                src="https://fastly.picsum.photos/id/64/4326/2884.jpg?hmac=9_SzX666YRpR_fOyYStXpfSiJ_edO3ghlSRnH2w09Kg"
              />
            </Avatar>
            <p className="text-sm">
              &quot;All courses are help people to achieve their goals&quot;
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
