import {
  FacebookIcon,
  InstagramIcon,
  HeartIcon,
  LinkedinIcon,
  XIcon,
} from "lucide-react";
import Link from "next/link";
import Logo from "./icons/logo";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Ka5QMRzDnte
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
export function Footer() {
  return (
    <footer className="container mx-auto mt-32 flex flex-col items-center justify-center rounded-t-xl bg-[#333333] text-white">
      <div className="mx-auto flex flex-col items-center justify-center px-4 py-12 sm:px-6 lg:px-8 lg:py-16">
        <div className="flex flex-col items-center justify-center xl:grid xl:grid-cols-5 xl:gap-8">
          <div className="flex flex-col items-center justify-center space-y-8 xl:col-span-1">
            <div className="flex items-center space-x-2">
              <div className="flex-shrink-0">
                <Logo />
              </div>
            </div>
            <div className="flex space-x-6">
              <Link className="text-gray-400 hover:text-gray-300" href="#">
                <FacebookIcon className="h-6 w-6" />
              </Link>
              <Link className="text-gray-400 hover:text-gray-300" href="#">
                <InstagramIcon className="h-6 w-6" />
              </Link>
              <Link className="text-gray-400 hover:text-gray-300" href="#">
                <LinkedinIcon className="h-6 w-6" />
              </Link>
              <Link className="text-gray-400 hover:text-gray-300" href="#">
                <XIcon className="h-6 w-6" />
              </Link>
            </div>
          </div>
          <div className="mt-12 flex  grid-cols-2 flex-col items-center justify-center gap-8 xl:col-span-4 xl:mt-0">
            <ul className="mt-4 flex flex-row flex-wrap items-center justify-center space-x-9 space-y-2">
              <li className="block text-center">
                <Link
                  className="block text-base text-gray-300 hover:text-white"
                  href="#"
                >
                  Home
                </Link>
              </li>
              <li className="block text-center">
                <Link
                  className="block text-base text-gray-300 hover:text-white"
                  href="#"
                >
                  Courses{" "}
                </Link>
              </li>
              <li className="block text-center">
                <Link
                  className="block text-base text-gray-300 hover:text-white"
                  href="#"
                >
                  Events
                </Link>
              </li>
              <li className="block text-center">
                <Link
                  className="block text-base text-gray-300 hover:text-white"
                  href="#"
                >
                  FAQs
                </Link>
              </li>
              <li className="block text-center">
                <Link
                  className="block text-base text-gray-300 hover:text-white"
                  href="#"
                >
                  Contact Us
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div className="flex w-full flex-col items-center justify-between gap-4 border-t border-gray-500 p-4 md:flex-row">
        <p className="flex items-center justify-end gap-2 text-center text-gray-400">
          Copyright © {new Date().getFullYear()} Bytecamp
        </p>
        <p className="flex items-center justify-end gap-2 text-nowrap text-center text-gray-400">
          Designed by
          <Link href="https://blackkspydo.com">blackkspydo</Link>
          with <HeartIcon style={{ fill: "red", stroke: "none" }} />
        </p>
      </div>
    </footer>
  );
}
