/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Kj0MFLxQnNF
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { JSX, SVGProps } from "react";

export function Hero() {
  return (
    <div className="relative  py-8">
      <div className="container mx-auto px-6">
        <div className="mt-12 flex flex-col items-center gap-12 lg:mt-28 lg:flex-row">
          <div className="flex-1">
            <h2 className="mb-8 text-5xl font-bold text-gray-800">
              Find suitable courses from the best
              <span className="text-[#F59E0B]">🎓</span>
              mentors{"\n                  "}
            </h2>
            <p className="mb-8 text-gray-600">
              The good gathering doesn&apos;t bearing day stars over open behold
              may male tree replenish don&apos;t blessed beast days earth fifth
              let multiply and he every blessed.
            </p>
            <div className="flex gap-4">
              <a
                className="rounded-md bg-[#10B981] px-6 py-3 font-semibold text-white hover:bg-[#059669]"
                href="#"
              >
                Start Learning
              </a>
              <a
                className="flex items-center text-[#10B981] hover:text-[#059669]"
                href="#"
              >
                Watch Video
                <CirclePlayIcon className="ml-2 h-6 w-6" />
              </a>
            </div>
          </div>
          <div className="relative flex-1">
            <img
              alt="Person teaching"
              className="rounded-xl"
              height="400"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/400",
                objectFit: "cover",
              }}
              width="400"
            />
            <div className="absolute right-0 top-0 w-72 rounded-lg bg-white p-6 shadow-lg">
              <div className="mb-4 flex items-center">
                <Avatar>
                  <AvatarImage
                    alt="Dennis Barrett"
                    src="/placeholder.svg?height=40&width=40"
                  />
                  <AvatarFallback>DB</AvatarFallback>
                </Avatar>
                <div className="ml-4">
                  <h4 className="text-lg font-semibold">UI Design Pattern</h4>
                  <p className="text-sm text-gray-600">Dennis Barrett</p>
                  <p className="text-sm text-gray-600">123 Courses</p>
                </div>
              </div>
              <Button className="w-full">Get started with EduLink</Button>
            </div>
            <div className="absolute -bottom-8 -right-8">
              <img
                alt="Person learning"
                className="rounded-xl"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
            </div>
          </div>
        </div>
      </div>
      <div className="absolute right-4 top-4 flex space-x-2">
        <XIcon className="h-6 w-6 text-gray-300" />
        <XIcon className="h-6 w-6 text-gray-300" />
        <XIcon className="h-6 w-6 text-gray-300" />
      </div>
    </div>
  );
}

function CirclePlayIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>,
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polygon points="10 8 16 12 10 16 10 8" />
    </svg>
  );
}

function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
