/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jTEmaKWuWxV
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Input } from "@/components/ui/input";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export function Login() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-100">
      <div className="w-full max-w-md space-y-6 rounded-lg bg-white p-8 shadow">
        <h1 className="text-center text-4xl font-bold">Log in</h1>
        <p className="text-center text-sm text-gray-600">
          Please fill your email and password to login
        </p>
        <form className="space-y-4">
          <div>
            <label
              className="block text-sm font-medium text-gray-700"
              htmlFor="email"
            >
              Email
            </label>
            <Input id="email" placeholder="Enter your email" type="email" />
          </div>
          <div>
            <label
              className="block text-sm font-medium text-gray-700"
              htmlFor="password"
            >
              Password
            </label>
            <Input
              id="password"
              placeholder="Enter your password"
              type="password"
            />
            <Link
              className="text-right text-sm text-blue-600 hover:underline"
              href="#"
            >
              Forgot password?
            </Link>
          </div>
          <Button className="w-full bg-green-600 text-white">Log In</Button>
        </form>
        <p className="text-center text-sm">
          Don&apos;t have an account?
          <Link className="font-medium text-blue-600 hover:underline" href="#">
            Sign up
          </Link>
        </p>
      </div>
    </div>
  );
}
