/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/sWvvcVE8975
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import Image from "next/image";
import {
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { JSX, SVGProps } from "react";

export function CourseCard() {
  return (
    <Card
      key="1"
      className="relative w-full min-w-[380px] max-w-[433px] rounded-[10px] border-none bg-white p-1"
    >
      <CardHeader className="absolute right-5 top-5 flex flex-row items-center gap-2 rounded-full border bg-white p-1">
        <Avatar>
          <AvatarImage
            alt="Billy Vasquez"
            className="object-cover"
            src="https://fastly.picsum.photos/id/64/4326/2884.jpg?hmac=9_SzX666YRpR_fOyYStXpfSiJ_edO3ghlSRnH2w09Kg"
          />
          <AvatarFallback>BV</AvatarFallback>
        </Avatar>
        <div className="mr-2 pb-2 text-sm font-semibold">Billy Vasquez</div>
      </CardHeader>
      <CardContent className="flex flex-col items-start p-2">
        <div className="mb-4 max-h-[250px] w-full overflow-hidden rounded-[10px]">
          <Image
            alt="Graphic Design Masterclass"
            className="h-full w-full"
            src="https://fastly.picsum.photos/id/20/3670/2462.jpg?hmac=CmQ0ln-k5ZqkdtLvVO23LjVAEabZQx2wOaT4pyeG10I"
            style={{
              aspectRatio: "128/128",
              objectFit: "cover",
            }}
            width="500"
            height="400"
          />
        </div>
        <div className="p-4">
          <div className="mb-3 text-xl font-bold">
            Graphic Design Masterclass
          </div>
          <div className="flex items-center justify-center space-x-4 text-sm text-gray-600">
            <div className="flex items-center justify-start gap-2">
              <ListIcon className="h-4 w-4" />
              <span className="whitespace-nowrap">140 Sections</span>
            </div>
            <div className="flex items-center justify-start gap-2">
              <CalendarIcon className="h-4 w-4" />
              <span className="whitespace-nowrap">90 Days</span>
            </div>
            <div className="flex items-center justify-start gap-2">
              <GroupIcon className="h-4 w-4" />
              <span className="whitespace-nowrap">80 Students</span>
            </div>
          </div>
        </div>
      </CardContent>
      <CardFooter className="pt-4">
        <div className="flex w-full flex-row items-center justify-start gap-4 text-center">
          <div className="text-2xl font-bold">$450.00 USD</div>
          <div className="text-sm text-gray-500 line-through">$4600.00 USD</div>
        </div>
      </CardFooter>
    </Card>
  );
}

function CalendarIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>,
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  );
}

function GroupIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 7V5c0-1.1.9-2 2-2h2" />
      <path d="M17 3h2c1.1 0 2 .9 2 2v2" />
      <path d="M21 17v2c0 1.1-.9 2-2 2h-2" />
      <path d="M7 21H5c-1.1 0-2-.9-2-2v-2" />
      <rect width="7" height="5" x="7" y="7" rx="1" />
      <rect width="7" height="5" x="10" y="12" rx="1" />
    </svg>
  );
}

function ListIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="8" x2="21" y1="6" y2="6" />
      <line x1="8" x2="21" y1="12" y2="12" />
      <line x1="8" x2="21" y1="18" y2="18" />
      <line x1="3" x2="3.01" y1="6" y2="6" />
      <line x1="3" x2="3.01" y1="12" y2="12" />
      <line x1="3" x2="3.01" y1="18" y2="18" />
    </svg>
  );
}
